case class FindByLocation(query: Option[String] = None,
                          state: Option[String] = None,
                          lat: Option[Double] = None,
                          lon: Option[Double] = None)

case class Property(id: String,
                    createdOn: Long,
                    price: Double,
                    currency: String,
                    place: String,
                    state: String,
                    lat: Double,
                    lon: Double,
                    priceUsd: Double,
                    priceLocal: Double,
                    surficeTotalSqm: Int,
                    surficeCoveredSqm: Int,
                    priceUsdPerSqm: Double,
                    pricePerSqm: Double,
                    floor: Int,
                    rooms: Int,
                    expenses: Int,
                    url: String,
//    description: String,
                    title: String,
                    imageUrl: String)
